app/src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Index(columns: ["isbn"], name: "isbn_idx")]
#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $isbn = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Assert\Date]
    private ?\DateTimeInterface $published = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cover_image = null;

    #[ORM\Column(type: Types::TEXT, length: 16383, nullable: false)]
    private string $long_description = '';

    #[ORM\Column(length: 2048, nullable: false)]
    private string $short_description = '';

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $status = null;

    #[ORM\ManyToMany(targetEntity: Author::class, mappedBy: 'books')]
    private Collection $authors;

    #[ORM\ManyToMany(targetEntity: Category::class, mappedBy: 'books')]
    private Collection $categories;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getTitle();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublished(): ?\DateTimeInterface
    {
        return $this->published;
    }

    public function setPublished(?\DateTimeInterface $published): static
    {
        $this->published = $published;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->cover_image;
    }

    public function setCoverImage(?string $cover_image): static
    {
        $this->cover_image = $cover_image;

        return $this;
    }

    public function getShortDescription(): string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): static
    {
        $this->short_description = $short_description ?? '';

        return $this;
    }

    public function getLongDescription(): string
    {
        return $this->long_description;
    }

    public function setLongDescription(?string $long_description): static
    {
        $this->long_description = $long_description ?? '';

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): static
    {
        if (!$this->authors->contains($author)) {
            $this->authors->add($author);
            $author->addBook($this);
        }

        return $this;
    }

    public function removeAuthor(Author $author): static
    {
        if ($this->authors->removeElement($author)) {
            $author->removeBook($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addBook($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        if ($this->categories->removeElement($category)) {
            $category->removeBook($this);
        }

        return $this;
    }
}

app/src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class BookController extends AbstractController
{
    #[Route('/book/{id}', name: 'app_book', requirements: ['id' => '\d+'])]
    public function index(Environment $twig, BookRepository $bookRepository, int $id): Response
    {
        $book = $bookRepository->find($id);
        $categories = $book->getCategories();
        $related = [];
        foreach ($categories as $category){
            $relatedBooks = $category->getBooks();
            foreach ($relatedBooks as $item) {
                if ($item->getId() !== $id)
                    $related[] = $item;
            }
        }
        shuffle( $related);
        $pickRandomTenOrLess = array_slice($related, 0, 7);

        return new Response($twig->render('book/index.html.twig', [
            'book' => $book,
            'related' => $pickRandomTenOrLess
        ]));
    }
}

app/templates/book/index.html.twig
{# templates/index.html.twig #}
{% extends 'base.html.twig' %}

{# ... #}

{% block body %}
    <div class="row">
        <div class="col-md-2 text-center">
            {% if book.coverImage %}
                <img class="cover-image" src="{{ asset('/uploads/images/' ~ book.coverImage) }}" />
            {% endif %}
        </div>
        <div class="col-md-10">
            <h2>
                {{ book.title }}
                {% if book.published %}
                    ({{ book.published|date('Y') }})
                {% endif %}
                <br>
                {% for author in book.authors %}
                    <small class="author-item">{{ author }}</small>
                {% endfor %}
            </h2>

            {% if book.longDescription %}
                <i>{{ book.longDescription }}</i>
            {% endif %}
            <div>
                <br><b>Артикул</b>: {{ book.isbn }}
                <br><b>Кол-во страниц</b>: {{ book.pages }}
                <br><b>Опубликовано</b>:
                {% if book.published %}
                    {{ book.published|date('d.m.Y') }}
                {% endif %}
                <br>
            </div>

            <ul class="list-inline list-category">
                {% for category in book.categories %}
                    <li>
                        <a class="btn btn-default btn-sm"  href="{{ path('app_category_view', { id: category.id }) }}">{{ category }}</a>
                    </li>
                {% endfor %}
            </ul>
            <b>Related books:</b>
            <ul class="list-inline">
                {% for item in related %}
                    <li>
                        <a href="{{ path('app_book', { id: item.id }) }}">{{ item.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {#        Книги из текущей категории(если имеются такие) (опционально)#}

{% endblock %}